package com.saion.core.model.notification

enum class NotificationType(val value: String) {
    CIRCLE_JOIN_COMPLETED("CIRCLE_JOIN_COMPLETED"),
    SCHEDULE_CREATED("SCHEDULE_CREATED"),
    SCHEDULE_DELETED("SCHEDULE_DELETED"),
    SCHEDULE_REMINDER_D7("SCHEDULE_REMINDER_D7"),
    SCHEDULE_REMINDER_D1("SCHEDULE_REMINDER_D1"),
    SCHEDULE_REMINDER_DDAY_ALL_DAY("SCHEDULE_REMINDER_DDAY_ALL_DAY"),
    SCHEDULE_REMINDER_DDAY_TIMED("SCHEDULE_REMINDER_DDAY_TIMED"),
    SCHEDULE_CONFIRMED_BY_FAMILY("SCHEDULE_CONFIRMED_BY_FAMILY"),
    SCHEDULE_CONFIRMATION_REQUESTED("SCHEDULE_CONFIRMATION_REQUESTED"),
    ;

    companion object {
        fun from(value: String): NotificationType? = entries.firstOrNull { it.value == value }
    }
}
